# Generated by Django 3.2.10 on 2022-01-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_date_update',
            new_name='date_update',
        ),
    ]
