# Generated by Django 3.2.10 on 2022-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_auto_20220105_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
