# Generated by Django 3.2.10 on 2022-01-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_auto_20220105_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(blank=True, max_length=50, null=True)),
                ('time_end', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.availabledate')),
            ],
        ),
    ]
