# Generated by Django 3.2.10 on 2022-01-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_availabledate_availabletimings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimings',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabletimings',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
