# Generated by Django 3.2.10 on 2022-01-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_availabledate_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='availabledate',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='availabletimings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='availabletimings',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
