# Generated by Django 3.2.10 on 2022-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0009_alter_availabledate_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledate',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
