# Generated by Django 3.2.10 on 2022-01-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0010_alter_availabledate_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='available_timings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultant.availabletimings'),
        ),
    ]
