# Generated by Django 3.2.10 on 2022-01-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0011_appointments_available_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
