# Generated by Django 3.2.10 on 2022-01-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0012_alter_appointments_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='amount',
            new_name='booking_Fee',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='discount',
            new_name='consulting_fee',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='sub_total',
        ),
    ]
