# Generated by Django 3.2.10 on 2022-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0014_appointments_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='client_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='client_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
