# Generated by Django 3.2.10 on 2022-01-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_consulting_fee_profile_consulting_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='consulting_Fee',
            new_name='consulting_fee',
        ),
    ]
